# Generated by Django 4.2.17 on 2024-12-06 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("genre", models.CharField(max_length=100)),
                ("score", models.DecimalField(decimal_places=1, max_digits=2)),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=1997,
                        validators=[
                            django.core.validators.MinValueValidator(1920),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                    ),
                ),
                ("developer", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
            ],
        ),
    ]
