# Generated by Django 4.2.17 on 2024-12-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("metascore", models.IntegerField(default=0)),
                ("console", models.CharField(default="NA", max_length=200)),
                ("userscore", models.CharField(default="0", max_length=3)),
                ("date", models.CharField(default="1998", max_length=100)),
            ],
        ),
    ]
