# Generated by Django 4.2.17 on 2024-12-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamelibrary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
