# Generated by Django 4.2.17 on 2024-12-06 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gamelibrary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="genre",
        ),
    ]
