# Generated by Django 4.2.17 on 2024-12-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamelibrary", "0002_alter_game_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
