# Generated by Django 4.2.17 on 2024-12-10 03:03

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Game = apps.get_model("gamelibrary", "Game")
    for game in Game.objects.all():
        if not game.slug:
            base_slug = slugify(f"{game.name} {game.console}")
            slug = base_slug
            counter = 1
            while Game.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            game.slug = slug
            game.save()


class Migration(migrations.Migration):

    dependencies = [
        ("gamelibrary", "0003_game_slug"),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
