# Generated by Django 4.2.17 on 2024-12-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamelibrary", "0004_auto_20241210_0303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
