# Generated by Django 4.2.17 on 2024-12-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamelibrary", "0005_alter_game_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="artwork_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
