# Generated by Django 4.2.17 on 2024-12-19 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamelibrary", "0009_alter_game_console_alter_game_cover_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="newdate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="cover_url",
            field=models.URLField(
                blank=True,
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.CharField(default="1998", max_length=100, null=True),
        ),
    ]
