# Generated by Django 4.2.17 on 2024-12-19 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamelibrary", "0011_auto_20241219_0813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.DateField(default=datetime.date(1998, 1, 1)),
        ),
    ]
